import csv
from pathlib import Path


def create_output_dirs():
    """
    Create output directories for reports and figures.

    Returns
    -------
    output_dir : Path
        Main output directory.

    figures_dir : Path
        Directory for saved figures.
    """

    output_dir = Path("outputs")
    figures_dir = output_dir / "figures"

    output_dir.mkdir(exist_ok=True)
    figures_dir.mkdir(exist_ok=True)

    return output_dir, figures_dir


def save_peak_report_csv(report, csv_path):
    """
    Save detected peak report to CSV.

    Parameters
    ----------
    report : list[dict]
        Peak report generated by build_peak_report.

    csv_path : Path
        Output CSV file path.
    """

    with open(csv_path, mode="w", newline="", encoding="utf-8") as file:
        writer = csv.writer(file)

        writer.writerow([
            "frequency_hz",
            "frequency_khz",
            "level_db",
            "snr_db",
        ])

        for row in report:
            writer.writerow([
                f"{row['frequency_hz']:.2f}",
                f"{row['frequency_khz']:.2f}",
                f"{row['level_db']:.2f}",
                f"{row['snr_db']:.2f}",
            ])